### PR TITLE
Added a recommendation on redriving messages from the DLQ to the source queue

### PR DESCRIPTION
**Pull request by udidahan**
*Description of changes:*

As in the title.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by udidahan** [comment]
Thanks so much @amboller !
I had already despaired that anything would come of this.

**Comment by amboller** [comment]
Happy to help!

**Comment by udidahan** [comment]
Just curious, how long is it expected to take for these changes to appear on the public site?

I'm not seeing this yet here:
https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-configure-dead-letter-queue-redrive.html

Or even in the Main branch in GitHub:
https://github.com/udidahan/amazon-sqs-developer-guide/blob/main/doc_source/sqs-configure-dead-letter-queue-redrive.md

**Review by amboller — COMMENTED** [review]
Approved

**Comment by udidahan** [comment]
Does "Approved" mean that you've kicked off the process to get these changes to percolate out to the public docs? If so, could you let me know how long it takes? That way I can avoid bugging you unnecessarily.

Thanks!

**Comment by amboller** [comment]
I see this note:

"It is recommended to start with a small value for "Custom Max Velocity" and verify that the source queue does not get overwhelmed with messages. From there gradually ramp up the "Custom Max Velocity" value, continuing to monitor the state of the source queue."

Published here:
- https://github.com/awsdocs/amazon-sqs-developer-guide/blob/main/doc_source/sqs-configure-dead-letter-queue-redrive.md

But not here.
- https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-configure-dead-letter-queue-redrive.html

 I will take care of this now. I will take care of this now. Publishing time takes about 2 hours. You should see the changes by 3 PM EST.

**Comment by udidahan** [comment]
I see that they're now live.

Thank you so much for the follow-up!

**Pull request merged**
